version: '3.4'

services:

    rmirpdb : 
        container_name: rmirpdb
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"
    

    user.api:
        container_name: "userapi"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "UserDatabaseSettings:ConnectionString=mongodb://root:hivi99Dasu@159.89.160.53:27017/?authSource=admin"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8000:80"
    issue.api:
        container_name: "issueapi"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "IssueDatabaseSettings:ConnectionString=mongodb://root:hivi99Dasu@159.89.160.53:27017/?authSource=admin"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8001:80"
    approve.api:
        container_name: "approveapi"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ApproveDatabaseSettings:ConnectionString=mongodb://root:hivi99Dasu@159.89.160.53:27017/?authSource=admin"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8002:80"
    workassign.api:
        container_name: "workassignapi"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "WorkDatabaseSettings:ConnectionString=mongodb://root:hivi99Dasu@159.89.160.53:27017/?authSource=admin"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8003:80"
    ucrdausers.api:
        container_name: "ucrdausersapi"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "UCRDAUserDatabaseSettings:ConnectionString=mongodb://root:hivi99Dasu@159.89.160.53:27017/?authSource=admin"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8004:80"
    apigateway:
        container_name: apigateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - user.api
            - issue.api
            - approve.api
            - workassign.api
            - ucrdausers.api
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "7000:80"